# Generated by Django 3.2.9 on 2021-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='extension',
            field=models.CharField(default='.jpg', max_length=8),
            preserve_default=False,
        ),
    ]
